from . import colors as COLORS


__BLOCK = 8

INTRO_POS = (0, 4 * __BLOCK)

MAIN_WIDTH = __BLOCK * 32
MAIN_HEIGHT = __BLOCK * 20

X_BOUNDS = (0, MAIN_WIDTH)
Y_BOUNDS = (0, MAIN_HEIGHT)

BRODY_X = __BLOCK * 15
BRODY_Y = __BLOCK
BRODY_WIDTH = __BLOCK * 2
BRODY_HEIGHT = __BLOCK * 2

BARRIER_WIDTH = __BLOCK
BARRIER_HEIGHT = __BLOCK

RES_ROOT = "res"
CAPTION = "Jaws"
FPS = 64
